version: '3.8'

services:
  app:
    image: hriqueximenes/sumologic:2.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    volumes:
      - ./scripts:/scripts