version: '3.8'

services:
  app:
    image: hriqueximenes/sumologic:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./scripts:/scripts